#!/usr/bin/make -f
#
# Makefile for KCEJ SDDRV/SDLIB
#

ifeq ($(wildcard PathDefs),)
PathDefs:
	iop-path-setup > PathDefs || (rm -f PathDefs ; exit 1)
endif
include PathDefs

#---------------------------------------------------------------
.PHONY: all clean

all:
	@echo "placeholder"
clean:
	@echo "placeholder"
